import type { LeaderboardResponse } from './types';

const now = Date.now();

export const mockLeaderboard: LeaderboardResponse = {
  updated_at: new Date(now - 2 * 60 * 1000).toISOString(),
  agents: [
    {
      id: 'apex',
      name: 'Apex',
      nickname: 'Tempo Reader',
      market_label: 'Kalshi crypto (KXBTC)',
      sprite_url: '/sprites/apex/rotations/south.png',
      total_pnl: 18.42,
      record: { W: 341, L: 298, BE: 11, settled: 650 },
      brier_7d: { value: 0.212, n: 142 },
      cities_or_tags: ['BTC', 'ETH'],
      moves: [
        { name: 'VR Gate', locked: false },
        { name: 'Momentum Direction', locked: false },
        { name: '???', locked: true },
        { name: '???', locked: true },
      ],
      open_position: {
        contract_ticker: 'KXBTC-26APR21-B67500',
        entry_price_cents: 42,
        side: 'yes',
        size: 12,
        entered_at_delayed: new Date(now - 45 * 60 * 1000).toISOString(),
        settles_at: new Date(now + 6 * 60 * 60 * 1000).toISOString(),
      },
      latest_receipt: {
        id: 'APX-20260421-014',
        contract_ticker: 'KXBTC-26APR20-B72000',
        side: 'no',
        entry_price_cents: 58,
        settle_price_cents: 100,
        size: 8,
        pnl: 33.6,
        settled_at: new Date(now - 18 * 60 * 60 * 1000).toISOString(),
      },
      state: 'live',
    },
    {
      id: 'gale',
      name: 'Gale',
      nickname: 'Weather Whisperer',
      market_label: 'Kalshi weather (KXHIGH)',
      sprite_url: '/sprites/gale/rotations/south.png',
      total_pnl: -22.89,
      record: { W: 22, L: 57, BE: 1, settled: 80 },
      brier_7d: { value: 0.088, n: 17 },
      cities_or_tags: ['MIA', 'LAX', 'NYC', 'CHI', 'DEN'],
      moves: [
        { name: 'Normal CDF', locked: false },
        { name: 'Seasonal Bias', locked: false },
        { name: '???', locked: true },
        { name: '???', locked: true },
      ],
      open_position: null,
      latest_receipt: {
        id: 'GAL-20260421-014',
        contract_ticker: 'KXHIGHMIA-26APR19-B85',
        side: 'yes',
        entry_price_cents: 29,
        settle_price_cents: 0,
        size: 3,
        pnl: -0.87,
        settled_at: new Date(now - 36 * 60 * 60 * 1000).toISOString(),
      },
      state: 'live',
    },
    {
      id: 'metheus',
      name: 'Metheus',
      nickname: 'Long Arc',
      market_label: 'TBD',
      sprite_url: '/sprites/metheus/rotations/south.png',
      total_pnl: 0,
      record: { W: 0, L: 0, BE: 0, settled: 0 },
      brier_7d: { value: 0, n: 0 },
      cities_or_tags: [],
      moves: [],
      open_position: null,
      latest_receipt: null,
      state: 'arriving_soon',
    },
  ],
};
